# Generated by Django 3.1.6 on 2021-02-18 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listing', '0002_auto_20210211_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, verbose_name=datetime.datetime(2021, 2, 18, 11, 46, 50, 267985)),
        ),
    ]
