# Generated by Django 3.1.6 on 2021-02-18 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('listing_id', models.IntegerField()),
                ('contact_date', models.DateTimeField(default=datetime.datetime(2021, 2, 18, 11, 46, 50, 267985))),
                ('name', models.CharField(max_length=200)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
