# Generated by Django 3.1.6 on 2021-02-19 15:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='listing_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 21, 24, 28, 598091)),
        ),
    ]
